default_language_version:
  python: python3

repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v4.4.0
    hooks:
      # Supported hooks: https://pre-commit.com/hooks.html
      - id: end-of-file-fixer
      - id: detect-private-key

  - repo: https://github.com/psf/black
    rev: 23.9.1  # You can specify the latest version here or leave it as is
    hooks:
      - id: black
        language_version: python3.10  # Replace with your Python version
        args: ["--line-length", "120"]
        verbose: true

  - repo: "https://github.com/astral-sh/ruff-pre-commit"
    rev: v0.6.5
    hooks:
      # Run the linter and fix problems.
      # * Must be run before ruff-format!
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
        verbose: true
  
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        types: [text, python]
        args: ["--builtin", "clear,rare,code"]
