default_language_version:
  python: python3

repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: detect-private-key

  # Remove the black hook entirely

  - repo: "https://github.com/astral-sh/ruff-pre-commit"
    rev: v0.6.5
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
        args: ["--line-length", "120"]  # Add this line to set the line length
        verbose: true
  
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        types: [text, python]
        args: ["--builtin", "clear,rare,code"]
