[tool.ruff]
line-length = 120
lint.select = ["E", "F", "D", "I"]
lint.ignore = ["D10", "D203", "D205", "D212", "D213", "D400", "D413", "D415", "D417"]
lint.extend-ignore = ["E501", "E302", "E303", "E305", "E306", "E231", "E203", "E202", "E201"]
